services:
  postgres:
    image: postgis/postgis:14-3.4
    restart: always
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${APP_DB}
      POSTGRES_USER: ${APP_USER}
      POSTGRES_PASSWORD: ${APP_PASSWORD}
    volumes:
      - app_postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_USER} -d ${APP_DB} -h 127.0.0.1" ]
      interval: 5s
      timeout: 3s
      retries: 20

  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "15432:${PGADMIN_LISTEN_PORT}"
    volumes:
      - pg_admin:/var/lib/pgadmin
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:${MINIO_VOLUMES}

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres:
  app_postgres:
  pg_admin:
  minio_data:
  grafana_data:
